#-------------------------------------------------------------------#
#--------------------------  Shiny Quizes --------------------------#
#-------------------------------------------------------------------#
# Developed by: Fender
# Part of the Shiny development branch.


#-------------------------------------------------------------------#
#-------------------------  General Values -------------------------#
#-------------------------------------------------------------------#

# Chat Prefix.
# Use the § character for color codes.
# ---dont use &---
# default: §5Shiny §dQuizes
ChatPrefix: §5Shiny §dQuizes


#-------------------------------------------------------------------#
#------------------------  Random Questions ------------------------#
#-------------------------------------------------------------------#

# General Question Values.

# If the plugin should ask random questions.
# default: true
enableRandomQuestions: true

# Time in seconds that the question is active.
# If there is no correct answer in the given time the question gets cancelled.
# and the answer is revealed.
# default: 30
QuestionTimeOutDelay: 30

# Time in seconds between automatically asking a question.
# default: 90
DelayBetweenQuestions: 90

# If the plugin should use the following question types.
# default: true
enableMathQuestions: true
# default: true
enableCustomQuestions: true

# Percent chance to actually ask a question, or to skip.
# If the percent chance is on 50, each time the delay is done it will have a 50% chance of actuallly asking a question.
# This can create more 'randomness' between questions.
# default: 33
PercentChanceForQuestion: 33





#-------------------------------------------------------------------#
#-------------------------  Math Questions -------------------------#
#-------------------------------------------------------------------#

# Math questions.
# The max values are the highest numbers that can be possible inside of a question.
# For example:
#
# If the PlusMaxValue is on 600, an example question can be:
# 600 + 214
# Either values can't go above 600. The answer can.

# Plus Questions
# default: 150
PlusQuestionMaxValue: 150

# Minus Questions
# default: 100
MinusQuestionMaxValue: 100
# If the answer of a minus question can be negative.
# For example: 20 - 84 = -64
# default: true
MinusQuestionAnswerCanBeNegative: true

# Multiplicity Questions.
# default: 25
MultiplyQuestionMaxValue: 25




#-------------------------------------------------------------------#
#------------ Not fully implemented yet. ignore for now ------------#
#-------------------------------------------------------------------#

# Keep track of an leaderboard.
EnableLeaderboard: false


# The reason to use an database is for speed and efficiency.
# Using a database on big servers increases performance.
# On small servers you can get away with using YML files.
# Please only use either one, not both.
EnableYML: true
enableMySQL: false

# MySQL atabase settings
# Only important if enableMySQL is on true.
DatabaseIPAdress: 1.1.1.1:3306
DatabaseName: ShinyQuizesLeaderboard
DatabaseUsername: Username
DatabasePassword: Password