#-------------------------------------------------------------------#
#--------------------------  Shiny Quizes --------------------------#
#-------------------------------------------------------------------#
# Developed by: Fender
# Part of the Shiny development branch.


#-------------------------------------------------------------------#
#-------------------------  General Values -------------------------#
#-------------------------------------------------------------------#

# Chat Prefix.
# Use the § character for color codes.
# ---dont use &---
# default: §5Shiny §dQuizes
ChatPrefix: §5Shiny §dQuizes

# Language to use
# Languages can be found / created in the language folder.
# default: english.properties
Language: english.properties

# Keep track of a leaderboard.
# default: true
EnableLeaderboard: true

# whether to give rewards when a player answers correctly.
# default: true
GiveRandomRewardOnCorrectAnswer: true

#-------------------------------------------------------------------#
#------------------------  Random Questions ------------------------#
#-------------------------------------------------------------------#

# General Question Values.

# If the plugin should ask random questions.
# default: true
enableRandomQuestions: true

# Tries its best to make sure the same type
# of question doesn't get asked multiple times in a row.
# default: true
enableRepeatingQuestionTypeProtection: true

# Time in seconds that the question is active.
# If there is no correct answer in the given time the question gets cancelled.
# and the answer is revealed.
# default: 30
QuestionTimeOutDelay: 30

# Time in seconds between automatically asking a question.
# default: 90
DelayBetweenQuestions: 90

# The color of the highlighted words.
# default: §b
HighlightedWordColor: §b

# If the plugin should use the following question types.
# default: true
enableMathQuestions: true
# default: true
enableCustomQuestions: true
# default: true
enableShuffledWordQuestions: true
# default: true
enableTypeWordQuestions: true
# default: true
enableAcronymWordQuestions: true

# If the question should be announced beforehand.
# default: false
enableRandomQuestionAnnouncement: true

# Time in seconds the announcement should be posted before the question.
# Must be higher than DelayBetweenQuestions.
# default: 15
RandomQuestionAnnouncementTimer: 15

# Percent chance to actually ask a question, or to skip.
# If the percent chance is on 50, each time the delay is done it will have a 50% chance of actuallly asking a question.
# This can create more 'randomness' between questions.
# default: 60 (60%)
PercentChanceForQuestion: 60


#-------------------------------------------------------------------#
#---------------------  ShuffledWord Questions ---------------------#
#-------------------------------------------------------------------#

# Shuffled questions with multiple words will keep the words seperated.
# example:
# word = Wither Rose
# enabled: eithWr sRoe
# disabled: rsR oeiWthe
#
# default: true
MakeShuffledQuestionsEasier: true

#-------------------------------------------------------------------#
#-------------------------  Math Questions -------------------------#
#-------------------------------------------------------------------#

# Math questions.
# The max values are the highest numbers that can be possible inside a question.
# For example:
#
# If the PlusMaxValue is on 600, an example question can be:
# 600 + 214
# Either values can't go above 600. The answer can.

# Plus Questions
# default: 150
PlusQuestionMaxValue: 150

# Minus Questions
# default: 100
MinusQuestionMaxValue: 100
# If the answer of a minus question can be negative.
# For example: 20 - 84 = -64
# default: true
MinusQuestionAnswerCanBeNegative: true

# Multiplicity Questions.
# default: 25
MultiplyQuestionMaxValue: 25




#-------------------------------------------------------------------#
#------------ Not fully implemented yet. ignore for now ------------#
#-------------------------------------------------------------------#

# The reason to use a database is for speed and efficiency.
# Using a database on big servers increases performance.
# On small servers you can get away with using YML files.
enableMySQL: false

# MySQL database settings
# Only important if enableMySQL is on true.
DatabaseIPAdress: 1.1.1.1:3306
DatabaseName: ShinyQuizesLeaderboard
DatabaseUsername: Username
DatabasePassword: Password