name: ShinyQuizes
version: '${project.version}'
main: shinyquizesplugin.shinyquizesplugin.ShinyQuizesPlugin
api-version: 1.19
authors: [ Fender ]
description: ShinyQuizes is a plugin to generate random quizes in chat.

commands:
  randomMathQuestion:
    description: Ask a random math question in chat.
    usage: /randomMathQuestion
    permission: ShinyQuizes.randomMathQuestion
  cancelCurrentQuestion:
    description: Cancels the current question.
    usage: /cancelCurrentQuestion
    permission: ShinyQuizes.cancelCurrentQuestion
  ShinyQuizes:
    description: Plugin specific commands.
    usage: /ShinyQuizes
    permission: ShinyQuizes.ShinyQuizesPlugin
  randomCustomQuestion:
    description: Ask a random custom question in chat.
    usage: /randomCustomQuestion
    permission: ShinyQuizes.randomCustomQuestion