name: ShinyQuizes
version: '${project.version}'
main: shinyquizesplugin.shinyquizesplugin.ShinyQuizesPlugin
api-version: 1.19
authors: [ Fender ]
description: ShinyQuizes is a plugin to generate random quizes in chat.
softdepend:
  - Vault

commands:
  ShinyQuizes:
    description: Plugin specific commands.
    usage: /ShinyQuizes
    permission: ShinyQuizes.ShinyQuizes
  QuizWins:
    description: Checks how many wins someone has.
    usage: /QuizWins
    permission: ShinyQuizes.QuizWins
  QuizLeaderboard:
    description: See the wins leaderboard.
    usage: /QuizLeaderboard
    permission: ShinyQuizes.QuizLeaderboard